project:
  type: website
  output-dir: docs
  preview:
    port: 5800
    browser: true
    watch-inputs: true
    navigate: true
author:
- id: wittkuhn
  name:
    given: Lennart
    family: Wittkuhn
    literal: Dr. Lennart Wittkuhn
  url: https://lennartwittkuhn.com/
  email: lennart.wittkuhn@uni-hamburg.de
  orcid: 0000-0003-2966-6888
  attributes:
    corresponding: true
  affiliations:
    - ref: uhh-psych
- id: hakimazar
  name:
    given: Reza
    family: Hakimazar
    literal: Reza Hakimazar
  email: reza.hakimazar@uni-hamburg.de
  url: https://rezahakimazar.github.io/
  attributes:
    corresponding: false
  affiliations:
    - ref: uhh-psych
- id: schuck
  name:
    given: Nicolas W.
    family: Schuck
    literal: Prof. Dr. Nicolas W. Schuck
  url: https://schucklab.gitlab.io/
  email: nicolas.schuck@uni-hamburg.de
  orcid: 0000-0002-0150-8776
  attributes:
    corresponding: true
  affiliations:
    - ref: uhh-psych
bibliography: references.bib
csl: apa.csl
metadata-files:
  - _affiliations.yml
  - _costs.yml

format:
  html:
    theme: [cosmo]
    anchor-sections: true
    smooth-scroll: true
    email-obfuscation: none
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "Contents"
    toc-expand: true
    number-sections: false
    cap-location: bottom
    page-layout: article
    code-fold: true
    code-overflow: wrap
    code-line-numbers: true
    code-copy: true
    code-link: false
    code-annotations: true
    code-tools:
      source: https://github.com/lnnrtwttkhn/fair-teaching-report
      toggle: true
      caption: "Code"
    engine: knitr
    highlight-style: monokai
    link-external-icon: false
    link-external-newwindow: true
    from: "markdown+emoji"
    search: false
    include-after-body: plausible.html
  pdf:
    toc: false
    include-in-header:
      - text: |
          \usepackage{style}
  docx: default